create table authors
(
    id         bigint generated by default as identity,
    first_name varchar(255),
    last_name  varchar(255),
    primary key (id)
);
create table books
(
    author_id         bigint,
    id                bigint generated by default as identity,
    description       varchar(255),
    first_name_author varchar(255),
    genre             varchar(255),
    last_name_author  varchar(255),
    name              varchar(255),
    primary key (id)
);
alter table if exists books
    add constraint fk foreign key (author_id) references authors
